networks:
  plms-network:
    external: true

volumes:
  postgresql-data:
    external: true
  mosquitto-data:
    external: true

services:
  db:
    image: postgres:17-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data:rw
      - ./db/config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - plms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      start_interval: 30s
      interval: 30s
      timeout: 10s
      retries: 5
  server:
    image: node:22-alpine
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/home/node/app
    working_dir: /home/node/app
    command: ["sh", "-c", "npm install && npm start"]
    networks:
      - plms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$APP_PORT || exit 1"]
      start_interval: 30s
      interval: 30s
      timeout: 10s
      retries: 5
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data:rw
      - ./mqtt/mosquitto/:/mosquitto/config:ro
    networks:
      - plms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -t test -C 1"]
      start_interval: 30s
      interval: 30s
      timeout: 10s
      retries: 5