services:

  db:
    image: postgres:17-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parking-system-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DATABASE"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    image: node:18-alpine
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/home/node/app
    working_dir: /home/node/app
    command: ["sh", "-c", "npm install && npm start"]
    networks:
      - parking-system-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./lorawan/mosquitto/:/mosquitto/config
      - mosquitto-data:/mosquitto/data
    networks:
      - parking-system-network
    restart: unless-stopped

volumes:
  db-data:
  mosquitto-data:

networks:
  parking-system-network:
    external: true