volumes:
  postgres-data:

networks:
  parking-net:

services:
  server:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - parking-net
    depends_on:
      - postgres
  postgres:
    image: docker.io/postgres:17.3-bookworm
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pas-website
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - parking-net
    ports:
      - "5432:5432"
