[general]
  # Log level
  #
  # debug=5, info=4, warning=3, error=2, fatal=1, panic=0
  log_level=5


# ChirpStack configuration.
[chirpstack]

  # API configuration.
  #
  # This configuration is used to automatically create the:
  #   * Device profile
  #   * Gateways
  #   * Application
  #   * Devices
  [chirpstack.api]

    # API key.
    #
    # The API key can be obtained through the ChirpStack web-interface.
    api_key=""

    # Server.
    #
    # This must point to the ChirpStack API interface.
    server="127.0.0.1:8080"

    # Insecure.
    #
    # Set this to true when the endpoint is not using TLS.
    insecure=true


    # MQTT integration configuration.
    #
    # This integration is used for counting the number of uplinks that are
    # published by the ChirpStack MQTT integration.
    [chirpstack.integration.mqtt]

    # MQTT server.
    server="127.0.0.1:1883"

    # Username.
    username=""

    # Password.
    password=""


  # MQTT gateway backend.
  [chirpstack.gateway.backend.mqtt]

    # MQTT server.
    server="127.0.0.1:1883"

    # Username.
    username=""

    # Password.
    password=""


# Simulator configuration.
#
# Example:
[[simulator]]

# Tenant ID.
#
# It is recommended to create a new tenant in ChirpStack.
tenant_id=""

# Duration.
#
# This defines the duration of the simulation. If set to '0s', the simulation
# will run until terminated. This includes the activation time.
duration="0s"

# Activation time.
#
# This is the time that the simulator takes to activate the devices. This
# value must be less than the simulator duration.
activation_time="10s"

  # Device configuration.
  [simulator.device]

  # Number of devices to simulate.
  count=5

  # Uplink interval.
  uplink_interval="5s"

  # FPort.
  f_port=10

  # Payload (HEX encoded).
  payload="5448452042554E4E4945532048415645204245454E2052454C4541534544"

  # Frequency (Hz).
  frequency=868100000

  # Bandwidth (Hz).
  bandwidth=125000

  # Spreading-factor.
  spreading_factor=7

  # Gateway configuration.
  [simulator.gateway]

  # Event topic template.
  event_topic_template="eu868/gateway/{{ .GatewayID }}/event/{{ .Event }}"

  # Command topic template.
  command_topic_template="eu868/gateway/{{ .GatewayID }}/command/{{ .Command }}"

  # Min number of receiving gateways.
  min_count=1

  # Max number of receiving gateways.
  max_count=1
