volumes:
  postgresql-data:
  redis-data:

networks:
  parking-net:

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    depends_on:
      - mosquitto
      - postgresql
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - POSTGRESQL_HOST=postgresql
      - REDIS_HOST=redis
    volumes:
      - ./config/chirpstack:/etc/chirpstack
    networks:
      - parking-net
    ports:
      - "8080:8080"
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    volumes:
      - ./config/mosquitto:/mosquitto/config
    networks:
      - parking-net
    ports:
      - "0.0.0.0:1883:1883"
  postgresql:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=chirpstack
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
    volumes:
      - ./config/postgresql:/docker-entrypoint-initdb.d
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - parking-net
  redis:
    image: redis:7-alpine
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - parking-net