volumes:
  postgresqldata:
    external: true

services:
  server:
    build: ./server
    env_file: ./server/.env
    restart: unless-stopped
    environment:
      - POSTGRESQL_HOST=postgres
    ports:
      - 127.0.0.1:8000:8000
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root
